import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProviderWrapper } from "../theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProviderWrapper>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ThemeProviderWrapper>
  );
}
